package FolderDifference.forms;


import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;

import javax.swing.*;
import java.awt.*;

/**
 * Created by Admin on 03.07.2016.
 */
public class MainForm extends JFrame {

    private JPanel mainPanel;
    private JTable table1;
    private JList list1;


    public MainForm() {
//        this.model = new MainModel(this);
//
//        //TODO: null pointer exception here
//        this.model.registerObserver(this);
//
//        this.controller = new MainController(this, this.model);
//
//        openButton1.addActionListener(controller);
//        openButton2.addActionListener(controller);
//        analyseButton.addActionListener(controller);
    }

    public static void main(String[] args) {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
        } catch (InstantiationException e) {
            e.printStackTrace();
        } catch (IllegalAccessException e) {
            e.printStackTrace();
        } catch (UnsupportedLookAndFeelException e) {
            e.printStackTrace();
        }

        JFrame frame = new JFrame("MainForm");
        frame.setContentPane(new MainForm().mainPanel);
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.pack();
        frame.setVisible(true);
    }

    public void onUpdate() {
//        dirPath1.setText(model.getDirectory1());
//        dirPath2.setText(model.getDirectory2());
//
//        onlyInDir1List.setListData(model.getOnlyInDir1().toArray());
//        onlyInDir2List.setListData(model.getOnlyInDir2().toArray());
    }

//    public String showFolderOpenDialog() {
//        String result = "";
//        JFileChooser fileChooser = new JFileChooser();
//        fileChooser.setCurrentDirectory(new File("."));
//        fileChooser.setDialogTitle("Select directory");
//        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
//        fileChooser.setDialogType(JFileChooser.OPEN_DIALOG);
//
//        int fileChooseResult = fileChooser.showDialog(this, "Open");
//        if (fileChooseResult == JFileChooser.APPROVE_OPTION) {
//            result = fileChooser.getSelectedFile().getPath();
//        }
//
//        return result;
//    }



    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(4, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), "xyz"));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));

    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
