package CredentialDetails.forms;


import CredentialDetails.app.ActionCommand;
import CredentialDetails.app.Application;
import CredentialDetails.controller.FileOperationController;
import CredentialDetails.controller.SectionsListSelectionListener;
import CredentialDetails.data.ApplicationModel;
import CredentialDetails.view.MainFormRender;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.table.DefaultTableModel;
import java.awt.*;

/**
 * Created by Admin on 03.07.2016.
 */
public class MainForm extends JFrame {

    private ApplicationModel model;

    private JPanel mainPanel;
    private JTable mainTable;
    private JList sectionsList;
    private JButton addEntryButton;
    private JButton deleteEntryButton;
    private JButton searchButton;
    private JButton loadButton;
    private JButton saveButton;
    private JScrollPane sectionsScrollPane;
    private JScrollPane credentialsScrollPane;
    private JSplitPane mainSplitPane;
    private JLabel statusBarLabel;
    private JButton button1;
    private JButton editEntryButton;

    /**
     * Constructor
     */
    public MainForm() {
        getContentPane().add(mainPanel);
        model = new ApplicationModel(new MainFormRender(this));

        // disable editing of all cells in the table
        mainTable.setModel(new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        });

        FileOperationController fileOperationController = new FileOperationController();
        loadButton.setActionCommand(ActionCommand.OPEN_FILE.name());
        loadButton.addActionListener(fileOperationController);
        saveButton.setActionCommand(ActionCommand.SAVE_FILE.name());
        saveButton.addActionListener(fileOperationController);

        sectionsList.addListSelectionListener(new SectionsListSelectionListener());
    }

    // Components' getters

    public ApplicationModel getModel() {
        return model;
    }

    public JList getSectionsList() {
        return sectionsList;
    }

    public JTable getMainTable() {
        return mainTable;
    }

    public JButton getLoadButton() {
        return loadButton;
    }

    public JButton getSaveButton() {
        return saveButton;
    }

    public JScrollPane getSectionsScrollPane() {
        return sectionsScrollPane;
    }

    public JSplitPane getMainSplitPane() {
        return mainSplitPane;
    }

    public JLabel getStatusBarLabel() {
        return statusBarLabel;
    }

    /**
     * Application starting point
     *
     * @param args arguments
     */
    public static void main(String[] args) {
        Application.getInstance().run();
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEmptyBorder(5, 5, 5, 5), null));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        mainPanel.add(panel1, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, null, null, null, 0, false));
        mainSplitPane = new JSplitPane();
        mainSplitPane.setContinuousLayout(true);
        mainSplitPane.setDividerLocation(100);
        panel1.add(mainSplitPane, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_BOTH, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_WANT_GROW, null, new Dimension(700, 300), null, 0, false));
        mainSplitPane.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), null));
        credentialsScrollPane = new JScrollPane();
        mainSplitPane.setRightComponent(credentialsScrollPane);
        credentialsScrollPane.setBorder(BorderFactory.createTitledBorder(null, "Credentials data", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.ABOVE_TOP));
        mainTable = new JTable();
        mainTable.setAutoCreateRowSorter(false);
        mainTable.setIntercellSpacing(new Dimension(1, 1));
        mainTable.setShowHorizontalLines(true);
        mainTable.setShowVerticalLines(true);
        credentialsScrollPane.setViewportView(mainTable);
        sectionsScrollPane = new JScrollPane();
        mainSplitPane.setLeftComponent(sectionsScrollPane);
        sectionsScrollPane.setBorder(BorderFactory.createTitledBorder(null, "Sections", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.ABOVE_TOP));
        sectionsList = new JList();
        sectionsList.setDropMode(DropMode.USE_SELECTION);
        sectionsList.setLayoutOrientation(0);
        final DefaultListModel defaultListModel1 = new DefaultListModel();
        defaultListModel1.addElement("123");
        defaultListModel1.addElement("345");
        sectionsList.setModel(defaultListModel1);
        sectionsList.setSelectionMode(0);
        sectionsList.putClientProperty("List.isFileList", Boolean.FALSE);
        sectionsScrollPane.setViewportView(sectionsList);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new GridLayoutManager(1, 2, new Insets(0, 0, 0, 0), -1, -1));
        panel1.add(panel2, new GridConstraints(1, 0, 1, 1, GridConstraints.ANCHOR_SOUTH, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW, GridConstraints.SIZEPOLICY_FIXED, new Dimension(-1, 20), new Dimension(-1, 20), null, 0, false));
        statusBarLabel = new JLabel();
        statusBarLabel.setText("Label");
        panel2.add(statusBarLabel, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final Spacer spacer1 = new Spacer();
        panel2.add(spacer1, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        final JToolBar toolBar1 = new JToolBar();
        toolBar1.setFloatable(false);
        mainPanel.add(toolBar1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_CENTER, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(-1, 20), null, 0, false));
        button1 = new JButton();
        button1.setIcon(new ImageIcon(getClass().getResource("/images/new-document.png")));
        button1.setText("");
        button1.setToolTipText("Create new file");
        toolBar1.add(button1);
        loadButton = new JButton();
        loadButton.setIcon(new ImageIcon(getClass().getResource("/images/open-file.png")));
        loadButton.setText("");
        loadButton.setToolTipText("Open file");
        toolBar1.add(loadButton);
        saveButton = new JButton();
        saveButton.setIcon(new ImageIcon(getClass().getResource("/images/save.png")));
        saveButton.setText("");
        saveButton.setToolTipText("Save to file");
        toolBar1.add(saveButton);
        final JToolBar.Separator toolBar$Separator1 = new JToolBar.Separator();
        toolBar1.add(toolBar$Separator1);
        addEntryButton = new JButton();
        addEntryButton.setHideActionText(false);
        addEntryButton.setHorizontalAlignment(0);
        addEntryButton.setIcon(new ImageIcon(getClass().getResource("/images/add-icon.png")));
        addEntryButton.setText("");
        addEntryButton.setToolTipText("Add new entry");
        toolBar1.add(addEntryButton);
        editEntryButton = new JButton();
        editEntryButton.setIcon(new ImageIcon(getClass().getResource("/images/edit.png")));
        editEntryButton.setText("");
        editEntryButton.setToolTipText("Edit selected entry");
        toolBar1.add(editEntryButton);
        deleteEntryButton = new JButton();
        deleteEntryButton.setIcon(new ImageIcon(getClass().getResource("/images/delete.png")));
        deleteEntryButton.setText("");
        deleteEntryButton.setToolTipText("Delete selected entry");
        toolBar1.add(deleteEntryButton);
        searchButton = new JButton();
        searchButton.setIcon(new ImageIcon(getClass().getResource("/images/search-icon.png")));
        searchButton.setText("");
        searchButton.setToolTipText("Search");
        toolBar1.add(searchButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}
